spring:
  application:
    name: demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1
          temperature: 0.2
      embedding:
        options:
          model: nomic-embed-text
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-h2db.sql
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: ragCodebase
  datasource:
    url: jdbc:h2:file:./chatMemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  docker:
    compose:
      file: ./docker-compose.yaml
      stop:
        command: down